apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jitsi-meet.jicofo.fullname" . }}
  labels:
    {{- include "jitsi-meet.jicofo.labels" . | nindent 4 }}
data:
  JVB_BREWERY_MUC: '{{ .Values.jvb.breweryMuc }}'
  XMPP_SERVER: '{{ include "jitsi-meet.xmpp.server" . }}'
  {{- if .Values.jibri.enabled }}
  JIBRI_BREWERY_MUC: '{{ .Values.jibri.breweryMuc }}'
  JIBRI_PENDING_TIMEOUT: '{{ .Values.jibri.timeout }}'
  {{- end }}
  {{- if .Values.jigasi.enabled }}
  JIGASI_BREWERY_MUC: '{{ .Values.jigasi.breweryMuc }}'
  JIGASI_SIP_URI: "available"
  {{- end }}
  {{- range $key, $value := .Values.jicofo.extraEnvs }}
  {{- if not (kindIs "invalid" $value) }}
  {{ $key }}: {{ tpl $value $ | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.octo.enabled }}
  ENABLE_OCTO: "1"
  OCTO_BRIDGE_SELECTION_STRATEGY: "SplitBridgeSelectionStrategy"
  {{- end }}
  JICOFO_ENABLE_REST: "1"
  {{- if .Values.global.webinar.enabled }}
  {{/* create a comma-separated list of visitor XMPP servers using the same logic as jitsi-meet.xmpp-visitor.servers, but per-replica */}}

  {{- $hosts := list -}}
  {{- $replica := "" -}}
  {{- range $i := until (int .Values.global.webinar.visitorProsodyCount) -}}
    {{- if $.Values.global.clusterDomain -}}
      {{- $replica = (printf "%s-%d.%s.svc.%s:5222" (include "jitsi-meet.prosody-visitor.fullname" $) $i $.Release.Namespace $.Values.global.clusterDomain) }}
    {{- else -}}
      {{- $replica = (printf "%s-%d.%s.svc:5222" (include "jitsi-meet.prosody-visitor.fullname" $) $i $.Release.Namespace) }}
    {{- end -}}
    {{- $hosts = append $hosts $replica }}
  {{- end }}

  VISITORS_XMPP_SERVER: '{{ join "," $hosts }}'
  {{- end }}