apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi-meet.jicofo.fullname" . }}
  labels:
    {{- include "jitsi-meet.jicofo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http-rest-api
    port: 8888
    targetPort: 8888
    protocol: TCP
  selector:
    {{- include "jitsi-meet.jicofo.selectorLabels" . | nindent 4 }}