{{- if and .Values.overlay.enabled (eq .Values.overlay.mode "v3") -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi-meet.overlay.v3.frontend.fullname" . }}
  labels:
    {{- include "jitsi-meet.overlay.v3.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.overlay.v3.frontend.service.type }}
  ports:
    - port: {{ .Values.overlay.v3.frontend.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "jitsi-meet.overlay.v3.frontend.selectorLabels" . | nindent 4 }}
{{- end -}}
