{{- if .Values.overlay.ingress.enabled -}}

{{- $fullName := "" -}}
{{- $svcPort := 0 -}}

{{- if eq .Values.overlay.mode "v1" -}}
    {{- $_ := set $ "fullName" (printf "%s-proxy" (include "jitsi-meet.overlay.v1.fullname" .)) -}}
    {{- $_ := set $ "svcPort" .Values.overlay.v1.proxy.service.port -}}
{{- else if eq .Values.overlay.mode "v3" -}}
    {{- $_ := set $ "fullName" (include "jitsi-meet.overlay.v3.frontend.fullname" .) -}}
    {{- $_ := set $ "svcPort" .Values.overlay.v3.frontend.service.port -}}
{{- end -}}
{{- $fullName := $.fullName -}}
{{- $svcPort := $.svcPort -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- if eq .Values.overlay.mode "v1" }}
        {{- include "jitsi-meet.overlay.v1.labels" . | nindent 4 }}
    {{- else if eq .Values.overlay.mode "v3" }}
        {{- include "jitsi-meet.overlay.v3.labels" . | nindent 4 }}
    {{- end }}
  annotations:
    nginx.org/websocket-services: {{ $fullName }}
    {{- if eq .Values.overlay.mode "v3" }}
    nginx.org/rewrites: "serviceName={{ include "jitsi-meet.overlay.v3.backend.fullname" . }} rewrite=/"
    {{- end }}
    {{- with .Values.overlay.ingress.annotations }}
    {{-   toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.overlay.ingress.ingressClassName }}
{{- if .Values.overlay.ingress.tls.enabled }}
  tls:
    - hosts:
      - {{ .Values.overlay.ingress.host | quote }}
      secretName: {{ .Values.overlay.ingress.tls.secretName }}
{{- end }}
  rules:
    - host: {{ .Values.overlay.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  {{- if kindIs "float64" $svcPort }}
                  number: {{ $svcPort }}
                  {{- else }}
                  name: {{ $svcPort }}
                  {{- end }}
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: {{ include "jitsi-meet.overlay.v3.backend.fullname" . }}
                port:
                  number: {{ .Values.overlay.v3.backend.service.port }}
{{- end }}
