{{- if .Values.overlay.ingress.enabled -}}

{{- $fullName := "" -}}
{{- $svcPort := 0 -}}

{{- if eq .Values.overlay.mode "v1" -}}
    {{- $_ := set $ "fullName" (printf "%s-proxy" (include "jitsi-meet.overlay.v1.fullname" .)) -}}
    {{- $_ := set $ "svcPort" .Values.overlay.v1.proxy.service.port -}}
{{- else if eq .Values.overlay.mode "v3" -}}
    {{- $_ := set $ "fullName" (include "jitsi-meet.overlay.v3.frontend.fullname" .) -}}
    {{- $_ := set $ "svcPort" .Values.overlay.v3.frontend.service.port -}}
{{- end -}}
{{- $fullName := $.fullName -}}
{{- $svcPort := $.svcPort -}}

{{- $websocketServices := $.fullName -}}
{{- if and .Values.excalidraw.backend.enabled (not .Values.excalidraw.useExternalExcalidraw) .Values.excalidraw.frontend.exposeViaIngress -}}
{{- $websocketServices = printf "%s,%s" $fullName (include "jitsi-meet.excalidraw.backend.fullname" .)  -}}
{{- end -}}

{{- $rewrites := "" -}}
{{- if eq .Values.overlay.mode "v3" -}}
{{- $rewrites = printf "serviceName=%s rewrite=/" (include "jitsi-meet.overlay.v3.backend.fullname" .) -}}
{{- end -}}
{{- if and .Values.excalidraw.backend.enabled (not .Values.excalidraw.useExternalExcalidraw) .Values.excalidraw.frontend.exposeViaIngress -}}
{{- $rewrites = printf "%s;serviceName=%s rewrite=/" $rewrites (include "jitsi-meet.excalidraw.backend.fullname" .) -}}
{{- end -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- if eq .Values.overlay.mode "v1" }}
        {{- include "jitsi-meet.overlay.v1.labels" . | nindent 4 }}
    {{- else if eq .Values.overlay.mode "v3" }}
        {{- include "jitsi-meet.overlay.v3.labels" . | nindent 4 }}
    {{- end }}
  annotations:
    nginx.org/websocket-services: {{ $websocketServices }}
    {{- if ne $rewrites "" }}
    nginx.org/rewrites: {{ $rewrites }}
    {{- end }}
    {{- with .Values.overlay.ingress.annotations }}
    {{-   toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.overlay.ingress.ingressClassName }}
{{- if .Values.overlay.ingress.tls.enabled }}
  tls:
    - hosts:
      - {{ .Values.overlay.ingress.host | quote }}
      secretName: {{ .Values.overlay.ingress.tls.secretName }}
{{- end }}
  rules:
    - host: {{ .Values.overlay.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  {{- if kindIs "float64" $svcPort }}
                  number: {{ $svcPort }}
                  {{- else }}
                  name: {{ $svcPort }}
                  {{- end }}
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: {{ include "jitsi-meet.overlay.v3.backend.fullname" . }}
                port:
                  number: {{ .Values.overlay.v3.backend.service.port }}
          {{- if and .Values.excalidraw.backend.enabled (not .Values.excalidraw.useExternalExcalidraw) .Values.excalidraw.frontend.exposeViaIngress }}
          - path: {{ .Values.excalidraw.frontend.ingressPath | default "/excalidraw/" }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "jitsi-meet.excalidraw.backend.fullname" . }}
                port:
                  number: 80
          {{- end }}
{{- end }}
