{{- if .Values.web.ingress.enabled -}}

{{- $fullName := "" -}}
{{- $svcPort := 0 -}}

{{- $_ := set $ "fullName" (include "jitsi-meet.web.fullname" .) -}}
{{- $_ := set $ "svcPort" .Values.web.service.port -}}

{{- $fullName := $.fullName -}}
{{- $svcPort := $.svcPort -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "jitsi-meet.web.labels" . | nindent 4 }}
  annotations:
    nginx.org/websocket-services: {{ $fullName }}
    {{- with .Values.web.ingress.annotations }}
    {{-   toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.web.ingress.ingressClassName }}
{{- if .Values.web.ingress.tls.enabled }}
  tls:
    - hosts:
      - {{ .Values.web.ingress.host | quote }}
      secretName: {{ .Values.web.ingress.tls.secretName }}
{{- end }}
  rules:
    - host: {{ .Values.web.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  {{- if kindIs "float64" $svcPort }}
                  number: {{ $svcPort }}
                  {{- else }}
                  name: {{ $svcPort }}
                  {{- end }}
{{- end }}
