{{- if and .Values.excalidraw.frontend.enabled (not .Values.excalidraw.useExternalExcalidraw) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi-meet.excalidraw.frontend.fullname" . }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    {{- include "jitsi-meet.excalidraw.frontend.selectorLabels" . | nindent 4 }}
{{- end }}