{{- range $shard, $e := until (int $.Values.global.webinar.visitorProsodyCount) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prosody-visitor.fullname" $ }}-{{ $shard }}
  labels:
    prosody-visitor-shard: {{ include "prosody-visitor.fullname" $ }}-{{ $shard }}
    {{- include "prosody-visitor.labels" $ | nindent 4 }}
  {{- with $.Values.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      prosody-visitor-shard: {{ include "prosody-visitor.fullname" $ }}-{{ $shard }}
      {{- include "prosody-visitor.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        prosody-visitor-shard: {{ include "prosody-visitor.fullname" $ }}-{{ $shard }}
        {{- include "prosody-visitor.selectorLabels" $ | nindent 8 }}
      {{- range $label, $value := mergeOverwrite $.Values.global.podLabels $.Values.podLabels }}
        {{ $label }}: {{ $value }}
      {{- end }}
      annotations:
        si.jit.meet/hash-secret: "{{ toYaml $.Values.secretEnvs | sha256sum | trunc 32 }}"
        si.jit.meet/hash-configmap: "{{ toYaml (concat $.Values.extraEnvs $.Values.extraEnvFrom) | sha256sum | trunc 32 }}"
        si.jit.meet/hash-cont-init: "{{ include (print $.Template.BasePath "/configmaps-cont-init.yaml") $ | sha256sum | trunc 32 }}"
      {{- range $annotation, $value := mergeOverwrite $.Values.global.podAnnotations $.Values.podAnnotations }}
        {{ $annotation }}: {{ $value }}
      {{- end }}
    spec:
    {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "prosody-visitor.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $.Chart.Name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.global.jitsiVersion | default $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ include "prosody-visitor.fullname" $ }}
          - secretRef:
              name: {{ include "prosody-visitor.fullname" $ }}
          {{- range $.Values.extraEnvFrom }}
          - {{ tpl (toYaml . ) $ | indent 12 | trim }}
          {{- end }}
          {{- if $.Values.global.releaseSecretsOverride.enabled }}
          {{- range $.Values.global.releaseSecretsOverride.extraEnvFrom }}
          - {{ tpl (toYaml . ) $ | indent 12 | trim }}
          {{- end }}
          {{- end }}
          env:
          - name: PROSODY_VISITOR_INDEX
            value: "{{ $shard }}"
          {{- if $.Values.enableAuth }}
          - name: ENABLE_AUTH
            value: "{{ $.Values.enableAuth }}"
          - name: AUTH_TYPE
            value: "{{ $.Values.authType }}"
          - name: JWT_APP_ID
            value: "{{ $.Values.jwt.appId }}"
          - name: JWT_APP_SECRET
            value: "{{ $.Values.jwt.secret }}"
          {{- end }}
          {{- if $.Values.turn.enabled }}
          - name: TURNS_HOST
            value: "{{ $.Values.turn.host }}"
          - name: TURNS_PORT
            value: "{{ $.Values.turn.port }}"
          {{- end }}
          {{- if $.Values.metrics.enabled }}
          - name: PROSODY_ENABLE_METRICS
            value: "true"
          - name: PROSODY_METRICS_ALLOWED_CIDR
            value: "{{ $.Values.metrics.allowed_cidr }}"
          {{- end }}
          {{- range $.Values.extraEnvs }}
          - {{ tpl (toYaml . ) $ | indent 12 | trim }}
          {{- end }}
          ports:
            - name: xmpp-c2s
              containerPort: {{ index $.Values.service.ports "xmpp-c2s" }}
              protocol: TCP
            - name: xmpp-s2s
              containerPort: {{ index $.Values.service.ports "xmpp-s2s" }}
              protocol: TCP
            - name: xmpp-component
              containerPort: {{ index $.Values.service.ports "xmpp-component" }}
              protocol: TCP
            - name: bosh-insecure
              containerPort: {{ index $.Values.service.ports "bosh-insecure" }}
              protocol: TCP
            - name: bosh-secure
              containerPort: {{ index $.Values.service.ports "bosh-secure" }}
              protocol: TCP
          {{- with $.Values.livenessProbe }}
          livenessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.readinessProbe }}
          readinessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          volumeMounts:
          - name: config
            mountPath: /config
          - name: prosody-data
            mountPath: {{ $.Values.dataDir }}
          - name: custom-cont-inits
            mountPath: /etc/cont-init.d/11-webinar-config
            subPath: 11-webinar-config
          {{- if $.Values.custom.contInit._10_config }}
          - name: custom-cont-inits
            mountPath: /etc/cont-init.d/10-config
            subPath: 10-config
          {{- end }}
          {{- if $.Values.custom.defaults._prosody_cfg_lua }}
          - name: custom-defaults
            mountPath: /defaults/prosody.cfg.lua
            subPath: prosody.cfg.lua
          {{- end }}
          {{- if $.Values.custom.defaults._saslauthd_conf }}
          - name: custom-defaults
            mountPath: /defaults/saslauthd.conf
            subPath: saslauthd.conf
          {{- end }}
          {{- if $.Values.custom.defaults._jitsi_meet_cfg_lua }}
          - name: custom-defaults
            mountPath: /defaults/conf.d/jitsi-meet.cfg.lua
            subPath: jitsi-meet.cfg.lua
          {{- end }}
          {{- with $.Values.extraVolumeMounts }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- if $.Values.metrics.enabled }}
        - name: metrics
          image: "{{ $.Values.metrics.image.repository }}:{{ $.Values.metrics.image.tag }}"
          imagePullPolicy: "{{ $.Values.metrics.image.pullPolicy }}"
          args: [--config=/etc/otel-collector-config.yaml]
          ports:
            - name: metrics
              containerPort: 8889
              protocol: TCP
          volumeMounts:
            - name: metrics-config
              mountPath: /etc/otel-collector-config.yaml
              subPath: otel-collector-config.yaml
              readOnly: true
        {{- end }}
      volumes:
      - name: config
        emptyDir: {}
      - name: custom-cont-inits
        configMap:
          defaultMode: 493
          name: {{ include "prosody-visitor.fullname" $ }}-cont-inits
          items:
            - key: 10-config
              path: 10-config
            - key: 11-webinar-config
              path: 11-webinar-config
      - name: custom-defaults
        configMap:
          name: {{ include "prosody-visitor.fullname" $ }}-defaults
          items:
            - key: prosody.cfg.lua
              path: prosody.cfg.lua
            - key: saslauthd.conf
              path: saslauthd.conf
            - key: jitsi-meet.cfg.lua
              path: jitsi-meet.cfg.lua
      - name: prosody-data
        emptyDir: {}
      {{- if $.Values.metrics.enabled }}
      - name: metrics-config
        configMap:
          name: "{{ include "prosody-visitor.fullname" $ }}-metrics"
          defaultMode: 420
      {{- end }}
      {{- with $.Values.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
