apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prosody-visitor.fullname" . }}
  labels:
    {{- include "prosody-visitor.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secretEnvs }}
  {{- if not (kindIs "invalid" $value) }}
  {{ $key }}: {{ tpl $value $ | b64enc }}
  {{- end }}
  {{- end }}
